permissions:
  contents: read
name: Run copy

on:
  push:
    branches:
      - master
      - develop
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  stub-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.4, 8.3, 8.2]
        laravel: [12]
        args: [""]
        include:
          - laravel: 12
            testbench: ^10.0

    name: Test Stubs - Laravel ${{ matrix.php }} - ${{ matrix.laravel }} ${{ matrix.args }} - ${{ matrix.os }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Create Laravel Project Directory
        run: mkdir laravel-app

      - name: Setup Laravel
        working-directory: laravel-app
        if: ${{ matrix.laravel != '12' }}
        run: |
          composer create-project laravel/laravel:^${{ matrix.laravel }}.0 .
          composer config repositories.bries '{"type": "path", "url": "../bries"}' --file composer.json

      - name: Setup Laravel (dev-master)
        working-directory: laravel-app
        if: ${{ matrix.laravel == '12' }}
        run: |
          composer create-project laravel/laravel:dev-master .
          composer config repositories.bries '{"type": "path", "url": "../bries"}' --file composer.json

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'bries'

      - name: Copy Bries stubs
        working-directory: laravel-app
        run: |
          composer require voorhof/bries:@dev --dev --prefer-dist --no-interaction --no-progress -W
          php artisan bries:copy ${{ matrix.args }}
